backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'static/uploads'
public_folder: 'uploads'

collections:
  - label: "Pages"
    name: "pages"
    folder: 'content/'
    create: true
    fields: # The fields for each document, usually in front matter
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Senast uppdaterad', name: 'date', widget: 'datetime' }
      - { label: 'Order (i meny)', name: 'order', widget: 'number' }
      - { label: 'Text', name: 'content', widget: 'markdown' }

